# Generated by Django 3.2.3 on 2021-05-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_mins', models.IntegerField()),
            ],
        ),
    ]
