# Generated by Django 3.2.3 on 2021-05-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifetrackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityinstance',
            name='begin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityinstance',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
