# Generated by Django 3.2.3 on 2021-05-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifetrackerapp', '0004_rename_activitytypes_userinstance_activity_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityinstance',
            name='description',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
