# Generated by Django 3.2.3 on 2021-05-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifetrackerapp', '0005_activityinstance_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityinstance',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
