# Generated by Django 3.2.3 on 2021-05-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifetrackerapp', '0006_alter_activityinstance_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityinstance',
            old_name='description',
            new_name='notes',
        ),
    ]
