# Generated by Django 3.2.3 on 2021-06-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifetrackerapp', '0007_rename_description_activityinstance_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=10000, null=True)),
                ('bin_activities_done', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='userinstance',
            name='bin_activity_types',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
