# Generated by Django 3.2.3 on 2021-06-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifetrackerapp', '0008_auto_20210611_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayinstance',
            name='id',
        ),
        migrations.AlterField(
            model_name='dayinstance',
            name='date',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
