# Generated by Django 3.2.3 on 2021-06-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifetrackerapp', '0009_auto_20210619_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayinstance',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
